# Generated by Django 4.0.2 on 2022-03-09 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_todo_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
